#!/usr/bin/env python3
"""Run Qwen v7 injection from a frozen official-pipeline Control trajectory.

Control is generated by the unmodified ``QwenImage21Pipeline.__call__`` path.
Its latent after the step immediately preceding ``inject_start`` is captured and
used as Treatment's starting state.  Treatment alone receives per-role v7 local
3D residuals; one missing or failed role does not invalidate other valid roles.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import shutil
import sys
import time
from pathlib import Path
from types import SimpleNamespace
from typing import Any

import numpy as np
import torch
from diffusers import QwenImage21Pipeline
from diffusers.models.transformers.transformer_qwenimage21 import QwenImage21KVCache
from diffusers.pipelines.qwenimage21.pipeline_qwenimage21 import (
    calculate_dimensions,
    calculate_shift,
    retrieve_timesteps,
)
from facexlib.parsing import init_parsing_model
from PIL import Image

PROJECT_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(PROJECT_ROOT))

from multishot.ip_adapter_experiment_utils import _face_app
from multishot.prompt_injection_safety import prompt_requests_closed_eyes
from pretest.evaluate_qwen_multiface_pair import run as evaluate_pair
from pretest.prepare_qwen_multiface_residual import prepare_from_image
from pretest.run_qwen_image21_multiface_residual import _encode_reference


def _sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(16 * 1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def _write(path: Path, payload: Any) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(payload, ensure_ascii=False, indent=2), encoding="utf-8")


def _invalidate_downstream_artifacts(output_dir: Path) -> None:
    """Remove only artifacts made stale by an explicit first-frame overwrite."""

    for relative in (
        "prepared/prepared.json",
        "prepared/preparation_attempt.json",
        "identity_metrics.json",
        "video_identity_metrics.json",
        "dino_identity_metrics.json",
        "comparison.jpg",
        "evaluation_comparison.jpg",
        "videos/control.mp4",
        "videos/treatment.mp4",
    ):
        (output_dir / relative).unlink(missing_ok=True)


def _decode(pipe, packed: torch.Tensor, width: int, height: int) -> Image.Image:
    latents = pipe._unpack_latents(packed, height, width, pipe.vae_scale_factor)
    latents = latents.to(pipe.vae.dtype)
    mean = (
        torch.tensor(pipe.vae.config.latents_mean)
        .view(1, pipe.vae.config.z_dim, 1, 1, 1)
        .to(latents.device, latents.dtype)
    )
    std = (
        torch.tensor(pipe.vae.config.latents_std)
        .view(1, pipe.vae.config.z_dim, 1, 1, 1)
        .to(latents.device, latents.dtype)
    )
    decoded = pipe.vae.decode(latents * std + mean, return_dict=False)[0][:, :, 0]
    return pipe.image_processor.postprocess(decoded, output_type="pil")[0]


def _official_control_and_fork_latent(
    pipe,
    record: dict,
    args: argparse.Namespace,
) -> tuple[Image.Image, torch.Tensor]:
    """Generate default Control and capture its exact latent entering injection."""

    captured: dict[str, torch.Tensor] = {}

    def capture_latent(pipeline, step_index, timestep, callback_kwargs):
        if step_index == args.inject_start - 1:
            captured["latents"] = callback_kwargs["latents"].detach().cpu().clone()
        return {}

    images = [
        Image.open(item["reference_image"]).convert("RGB")
        for item in record["characters"]
    ]
    generator = torch.Generator(device="cuda").manual_seed(record["seed"])
    control = pipe(
        prompt=record["qwen_prompt"],
        image=images,
        width=args.width,
        height=args.height,
        num_inference_steps=args.steps,
        generator=generator,
        true_cfg_scale=1.0,
        output_resolution=args.output_resolution,
        use_kv_cache=args.use_kv_cache,
        callback_on_step_end=capture_latent,
        callback_on_step_end_tensor_inputs=["latents"],
    ).images[0]
    if "latents" not in captured:
        raise RuntimeError(
            f"Official Control did not expose the latent entering step {args.inject_start}"
        )
    return control, captured["latents"]


def _euler_step(
    sample: torch.Tensor,
    model_output: torch.Tensor,
    sigmas: torch.Tensor,
    step_index: int,
) -> torch.Tensor:
    # Exact deterministic branch of FlowMatchEulerDiscreteScheduler.step().
    dt = sigmas[step_index + 1] - sigmas[step_index]
    return (sample.float() + dt * model_output.float()).to(model_output.dtype)


def _prepare_conditioning(pipe, record: dict, args: argparse.Namespace) -> dict:
    device = pipe._execution_device
    condition_images = [
        Image.open(item["reference_image"]).convert("RGBA")
        for item in record["characters"]
    ]
    input_sizes, input_images, vae_images = [], [], []
    for image in condition_images:
        input_width, input_height, _ = calculate_dimensions(
            args.output_resolution * args.output_resolution,
            image.width / image.height,
        )
        input_sizes.append((input_width, input_height))
        input_images.append(
            pipe.image_processor.resize(image, width=input_width, height=input_height)
        )
        vae_images.append(
            pipe.image_processor.preprocess(
                image, width=input_width, height=input_height
            ).unsqueeze(2)
        )

    prompt_embeds, prompt_mask, image_pad_mask = pipe.encode_prompt(
        image=input_images,
        prompt=record["qwen_prompt"],
        device=device,
        num_images_per_prompt=1,
    )
    generator = torch.Generator(device="cuda").manual_seed(record["seed"])
    latent_channels = pipe.transformer.config.in_channels
    initial, condition_latents = pipe.prepare_latents(
        vae_images,
        1,
        latent_channels,
        args.height,
        args.width,
        prompt_embeds.dtype,
        device,
        generator,
        None,
    )
    latent_height = 2 * (args.height // (pipe.vae_scale_factor * 2))
    latent_width = 2 * (args.width // (pipe.vae_scale_factor * 2))
    img_shapes = [[
        *[
            (1, image_height // pipe.vae_scale_factor, image_width // pipe.vae_scale_factor)
            for image_width, image_height in input_sizes
        ],
        (1, args.height // pipe.vae_scale_factor, args.width // pipe.vae_scale_factor),
    ]]
    image_pad_mask = torch.cat(
        [
            image_pad_mask,
            image_pad_mask.new_ones(image_pad_mask.shape[0], initial.shape[1] // 4),
        ],
        dim=1,
    )
    sigmas_input = np.linspace(1.0, 1 / args.steps, args.steps)
    mu = calculate_shift(
        initial.shape[1],
        pipe.scheduler.config.get("base_image_seq_len", 256),
        pipe.scheduler.config.get("max_image_seq_len", 4096),
        pipe.scheduler.config.get("base_shift", 0.5),
        pipe.scheduler.config.get("max_shift", 1.15),
    )
    timesteps, _ = retrieve_timesteps(
        pipe.scheduler, args.steps, device, sigmas=sigmas_input, mu=mu
    )
    cache = (
        QwenImage21KVCache(len(pipe.transformer.transformer_blocks))
        if args.use_kv_cache and pipe.transformer.config.causal_condition
        else None
    )
    return {
        "device": device,
        "prompt_embeds": prompt_embeds,
        "prompt_mask": prompt_mask,
        "image_pad_mask": image_pad_mask,
        "condition_latents": condition_latents,
        "initial": initial,
        "latent_height": latent_height,
        "latent_width": latent_width,
        "img_shapes": img_shapes,
        "timesteps": timesteps,
        "sigmas": pipe.scheduler.sigmas,
        "cache": cache,
    }


def _predict(pipe, state: dict, latents: torch.Tensor, step_index: int) -> torch.Tensor:
    t = state["timesteps"][step_index]
    model_input = torch.cat([state["condition_latents"], latents], dim=1)
    timestep = t.expand(latents.shape[0]).to(latents.dtype)
    cache = state["cache"]
    kv_mode = "extract" if cache is not None and step_index == 0 else (
        "cached" if cache is not None else None
    )
    with pipe.transformer.cache_context("cond"):
        prediction = pipe.transformer(
            hidden_states=model_input,
            timestep=timestep / 1000,
            encoder_hidden_states=state["prompt_embeds"],
            encoder_hidden_states_mask=state["prompt_mask"],
            img_shapes=state["img_shapes"],
            img_mask=state["image_pad_mask"],
            attention_kwargs={},
            kv_cache=cache,
            kv_cache_mode=kv_mode,
            return_dict=False,
        )[0]
    return prediction[:, -latents.size(1) :]


def _target_records(
    pipe,
    prepared: dict,
    state: dict,
    args: argparse.Namespace,
    seed: int,
) -> tuple[list[dict], list[dict]]:
    records = []
    failures = []
    assignment_cosines = {
        item["character"]: float(item["cosine"])
        for item in prepared["assignment"]["pairs"]
    }
    generator = torch.Generator(device="cuda").manual_seed(seed)
    for target in prepared["targets"]:
        try:
            reference_x0 = _encode_reference(
                pipe,
                Image.open(target["harmonized_reference"]),
                args.width,
                args.height,
                generator,
            ).to(device=state["device"], dtype=torch.bfloat16)
            mask = Image.open(target["mask"]).convert("L").resize(
                (state["latent_width"], state["latent_height"]),
                Image.Resampling.BILINEAR,
            )
            alpha = torch.from_numpy(np.asarray(mask, dtype=np.float32) / 255.0)
            alpha = alpha.reshape(
                1, state["latent_height"] * state["latent_width"], 1
            )
            alpha = alpha.to(device=state["device"], dtype=torch.bfloat16)
            bbox = target["bbox"]
            face_height = max(1.0, float(bbox[3] - bbox[1]))
            size_scale = min(1.0, max(0.3, face_height / 128.0))
            identity_cosine = assignment_cosines[target["name"]]
            if identity_cosine < args.identity_step_threshold:
                active_steps = args.low_identity_active_steps
                schedule_class = "low_identity_six_steps"
            else:
                active_steps = args.high_identity_active_steps
                schedule_class = "high_identity_one_step"
            records.append({
                **target,
                "reference_x0": reference_x0,
                "alpha": alpha,
                "size_scale": size_scale,
                "effective_strength": args.injection_strength * size_scale,
                "step12_identity_cosine": identity_cosine,
                "identity_step_threshold": args.identity_step_threshold,
                "active_injection_steps": int(active_steps),
                "schedule_class": schedule_class,
            })
        except Exception as exc:
            failures.append({
                "name": target["name"],
                "reason": "latent_reference_preparation_failed",
                "error": repr(exc),
            })
    return records, failures


def _fallback_reason(exc: Exception) -> str:
    message = str(exc).lower()
    if "detected 0 reliable faces" in message:
        return "no_reliable_face_detected"
    if "reliable faces" in message or "expected" in message and "faces" in message:
        return "reliable_face_detection_failed"
    if "color-safe identity injection core is empty" in message:
        return "empty_v7_color_safe_core"
    if "render" in message or "pose" in message:
        return "gaussian_render_or_pose_check_failed"
    return "reference_preparation_failed"


def _finish_control_reuse(
    control_path: Path,
    output_dir: Path,
    record: dict,
    args: argparse.Namespace,
    step_log: list[dict],
    started: float,
    reason: str,
    error: str | None = None,
) -> dict:
    for index in range(args.inject_start, args.steps):
        step_log.append({
            "step": index,
            "branch": "official_control_reuse",
            "injected": False,
            "active_characters": [],
            "residual_norm": 0.0,
        })
    treatment_path = output_dir / "treatment.png"
    shutil.copy2(control_path, treatment_path)
    result = {
        "kind": "qwen_image21_official_control_fork_adaptive_v7",
        "injection_applied": False,
        "status": "treatment_reuses_control",
        "reason": reason,
        "error": error,
        "run": record["run"],
        "shot_key": record["shot_key"],
        "prompt": record["qwen_prompt"],
        "seed": record["seed"],
        "steps": args.steps,
        "inject_start": args.inject_start,
        "protocol": "official default Control; captured step-12 latent; gated Control reuse",
        "control_generation": "QwenImage21Pipeline.__call__",
        "control": str(control_path.resolve()),
        "treatment": str(treatment_path.resolve()),
        "control_sha256": _sha256(control_path),
        "treatment_sha256": _sha256(treatment_path),
        "identity_step_threshold": args.identity_step_threshold,
        "requested_characters": [item["name"] for item in record["characters"]],
        "applied_characters": [],
        "skipped_characters": [item["name"] for item in record["characters"]],
        "target_failures": [],
        "step_log": step_log,
        "elapsed_seconds": round(time.perf_counter() - started, 3),
        "peak_cuda_memory_mib": round(torch.cuda.max_memory_allocated() / 1024**2, 2),
    }
    _write(output_dir / "result.json", result)
    return result


@torch.no_grad()
def run_shot(
    pipe,
    app,
    parser,
    record: dict,
    output_dir: Path,
    args: argparse.Namespace,
) -> dict:
    started = time.perf_counter()
    output_dir.mkdir(parents=True, exist_ok=True)
    if args.overwrite:
        _invalidate_downstream_artifacts(output_dir)
    pipe._attention_kwargs = {}
    control_image, captured_latent = _official_control_and_fork_latent(
        pipe, record, args
    )
    control_path = output_dir / "control.png"
    treatment_path = output_dir / "treatment.png"
    control_image.save(control_path)

    # Rebuild only the immutable condition state needed by Treatment.  The
    # noisy target state itself comes from the official Control trajectory.
    state = _prepare_conditioning(pipe, record, args)
    if state["cache"] is not None:
        # Prefill the step-independent text/reference-image KV cache.  The
        # resulting target prediction is intentionally discarded.
        _predict(pipe, state, state["initial"], 0)
    current = captured_latent.to(
        device=state["device"], dtype=state["initial"].dtype
    )
    if current.shape != state["initial"].shape:
        raise RuntimeError(
            f"Captured latent shape {tuple(current.shape)} does not match "
            f"conditioning shape {tuple(state['initial'].shape)}"
        )
    step_log = [
        {"step": index, "branch": "official_control_prefix", "injected": False}
        for index in range(args.inject_start)
    ]

    detect_prediction = _predict(pipe, state, current, args.inject_start)
    sigma = state["sigmas"][args.inject_start].to(
        device=current.device, dtype=current.dtype
    )
    pred_x0 = current - sigma * detect_prediction
    preview = _decode(pipe, pred_x0, args.width, args.height)
    prepared_dir = output_dir / "prepared"
    if prompt_requests_closed_eyes(record["official_prompt"]):
        prepared_dir.mkdir(parents=True, exist_ok=True)
        preview.save(prepared_dir / "pred_x0.png")
        return _finish_control_reuse(
            control_path, output_dir, record, args, step_log, started,
            "prompt_eye_closure_conflict",
        )
    try:
        prepared = prepare_from_image(
            preview=preview,
            characters_spec=record["characters"],
            output_dir=prepared_dir,
            minimum_confidence=args.min_face_confidence,
            app=app,
            parser=parser,
            preview_source=(
                f"Qwen official-Control captured latent pred_x0 at step "
                f"{args.inject_start}"
            ),
        )
        if not prepared["targets"]:
            raise RuntimeError(
                "No detected role produced a usable v7 reference: "
                + json.dumps(prepared.get("target_failures", []), ensure_ascii=False)
            )
        targets, latent_target_failures = _target_records(
            pipe, prepared, state, args, record["seed"]
        )
        if not targets:
            raise RuntimeError(
                "No prepared role produced an encodable v7 latent reference: "
                + json.dumps(latent_target_failures, ensure_ascii=False)
            )
    except Exception as exc:
        return _finish_control_reuse(
            control_path, output_dir, record, args, step_log, started,
            _fallback_reason(exc), repr(exc),
        )

    treatment = current.clone()
    end_step = min(
        args.steps,
        args.inject_start + max(target["active_injection_steps"] for target in targets),
    )
    for index in range(args.inject_start, args.steps):
        treatment_prediction = (
            detect_prediction
            if index == args.inject_start
            else _predict(pipe, state, treatment, index)
        )
        treatment_base = _euler_step(
            treatment, treatment_prediction, state["sigmas"], index
        )
        active_targets = [
            target
            for target in targets
            if index < args.inject_start + target["active_injection_steps"]
        ]
        active = bool(active_targets)
        residual = torch.zeros_like(treatment_base)
        active_names = []
        if active:
            sigma_next = state["sigmas"][index + 1].to(
                device=treatment.device, dtype=treatment.dtype
            )
            alphas, references = [], []
            for target in active_targets:
                alphas.append(target["alpha"] * target["effective_strength"])
                references.append(
                    sigma_next * state["initial"]
                    + (1.0 - sigma_next) * target["reference_x0"]
                )
            alpha_stack = torch.stack(alphas, dim=0)
            alpha_sum = alpha_stack.sum(dim=0)
            normalization = torch.where(
                alpha_sum > 1.0,
                alpha_sum.reciprocal(),
                torch.ones_like(alpha_sum),
            )
            normalized = alpha_stack * normalization.unsqueeze(0)
            for alpha, reference_state in zip(normalized, references):
                residual = residual + alpha * (reference_state - treatment_base)
            active_names = [target["name"] for target in active_targets]
        treatment_next = treatment_base + residual
        step_log.append({
            "step": index,
            "branch": "forked",
            "injected": active,
            "active_characters": active_names,
            "residual_norm": float(residual.float().norm().cpu()),
        })
        treatment = treatment_next

    _decode(pipe, treatment, args.width, args.height).save(treatment_path)

    serializable_targets = [
        {key: value for key, value in target.items() if key not in {"alpha", "reference_x0"}}
        for target in targets
    ]
    result = {
        "kind": "qwen_image21_official_control_fork_adaptive_v7",
        "injection_applied": True,
        "run": record["run"],
        "shot_key": record["shot_key"],
        "prompt": record["qwen_prompt"],
        "seed": record["seed"],
        "steps": args.steps,
        "inject_start": args.inject_start,
        "end_step_exclusive": end_step,
        "protocol": "official default Control; captured step-12 latent forks Treatment",
        "control_generation": "QwenImage21Pipeline.__call__",
        "identity_step_threshold": args.identity_step_threshold,
        "low_identity_active_steps": args.low_identity_active_steps,
        "high_identity_active_steps": args.high_identity_active_steps,
        "control": str(control_path.resolve()),
        "treatment": str(treatment_path.resolve()),
        "control_sha256": _sha256(control_path),
        "treatment_sha256": _sha256(treatment_path),
        "prepared": str((prepared_dir / "prepared.json").resolve()),
        "targets": serializable_targets,
        "requested_characters": prepared["requested_characters"],
        "unassigned_scheduled_characters": prepared[
            "unassigned_scheduled_characters"
        ],
        "target_failures": prepared["target_failures"] + latent_target_failures,
        "applied_characters": [target["name"] for target in targets],
        "skipped_characters": [
            name
            for name in prepared["requested_characters"]
            if name not in {target["name"] for target in targets}
        ],
        "step_log": step_log,
        "elapsed_seconds": round(time.perf_counter() - started, 3),
        "peak_cuda_memory_mib": round(torch.cuda.max_memory_allocated() / 1024**2, 2),
    }
    _write(output_dir / "result.json", result)
    try:
        metrics = evaluate_pair(
            SimpleNamespace(
                prepared=prepared_dir / "prepared.json",
                control=control_path,
                treatment=treatment_path,
                output=output_dir / "identity_metrics.json",
                min_face_confidence=args.min_face_confidence,
            ),
            app=app,
        )
        result["identity_metrics"] = metrics
    except Exception as exc:
        # Pair generation is the expensive result.  A per-shot metric failure
        # must not abort the batch because the canonical evaluation pass below
        # recomputes all first-frame metrics from the saved images.
        result["identity_evaluation_error"] = repr(exc)
    _write(output_dir / "result.json", result)
    return result


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--model",
        type=Path,
        default=PROJECT_ROOT / "models/diffusion/qwen-image-2.1",
    )
    parser.add_argument(
        "--manifest",
        type=Path,
        default=PROJECT_ROOT
        / "outputs/entitybench_qwen_image21_v7_full3/manifest.json",
    )
    parser.add_argument(
        "--output-root",
        type=Path,
        default=PROJECT_ROOT
        / "outputs/entitybench_qwen_image21_official_control_partial_adaptive_040_full3",
    )
    parser.add_argument(
        "--shot",
        action="append",
        default=None,
        help="RUN/SCENE:SHOT; repeatable",
    )
    parser.add_argument("--width", type=int, default=1024)
    parser.add_argument("--height", type=int, default=576)
    parser.add_argument("--output-resolution", type=int, default=1024)
    parser.add_argument("--steps", type=int, default=20)
    parser.add_argument("--inject-start", type=int, default=12)
    parser.add_argument("--injection-strength", type=float, default=0.4)
    parser.add_argument("--identity-step-threshold", type=float, default=0.40)
    parser.add_argument("--low-identity-active-steps", type=int, default=6)
    parser.add_argument("--high-identity-active-steps", type=int, default=1)
    parser.add_argument("--min-face-confidence", type=float, default=0.5)
    parser.add_argument("--use-kv-cache", action=argparse.BooleanOptionalAction, default=True)
    parser.add_argument("--overwrite", action="store_true")
    parser.add_argument(
        "--summarize-only",
        action="store_true",
        help="Rebuild the adaptive manifest and summary without loading the model.",
    )
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    if not 0.0 <= args.identity_step_threshold <= 1.0:
        raise ValueError("--identity-step-threshold must be in [0, 1]")
    if args.low_identity_active_steps != 6 or args.high_identity_active_steps != 1:
        raise ValueError("The canonical adaptive policy is fixed to low=6 and high=1 steps")
    manifest = json.loads(args.manifest.read_text(encoding="utf-8"))
    selected = set(args.shot or [
        f"{record['run']}/{record['shot_key']}" for record in manifest["shots"]
    ])
    records = [
        record
        for record in manifest["shots"]
        if f"{record['run']}/{record['shot_key']}" in selected
    ]
    missing = selected - {f"{record['run']}/{record['shot_key']}" for record in records}
    if missing:
        raise ValueError(f"Unknown shots: {sorted(missing)}")
    results = []
    if not args.summarize_only:
        pipe = QwenImage21Pipeline.from_pretrained(
            str(args.model.resolve()), dtype=torch.bfloat16, local_files_only=True
        )
        pipe.enable_sequential_cpu_offload()
        app = _face_app()
        parser = init_parsing_model(model_name="bisenet", device=torch.device("cuda"))
        for record in records:
            shot_dir = (
                args.output_root.resolve()
                / record["run"]
                / "shots"
                / f"shot_{record['shot_key'].replace(':', '_')}"
            )
            if (shot_dir / "result.json").is_file() and not args.overwrite:
                print(f"exists {record['run']} {record['shot_key']}", flush=True)
                continue
            torch.cuda.reset_peak_memory_stats()
            print(f"running {record['run']} {record['shot_key']}", flush=True)
            results.append(run_shot(pipe, app, parser, record, shot_dir, args))
    all_results = []
    for path in sorted(args.output_root.resolve().glob("*/shots/shot_*/result.json")):
        all_results.append(json.loads(path.read_text(encoding="utf-8")))
    result_lookup = {(item["run"], item["shot_key"]): item for item in all_results}
    pilot_manifest = {
        "kind": "qwen_image21_official_control_partial_adaptive_manifest",
        "shot_count": len(all_results),
        "shots": [
            {
                **record,
                "shot_dir": str(
                    (
                        args.output_root.resolve()
                        / record["run"]
                        / "shots"
                        / f"shot_{record['shot_key'].replace(':', '_')}"
                    ).resolve()
                ),
            }
            for record in manifest["shots"]
            if (record["run"], record["shot_key"]) in result_lookup
        ],
    }
    _write(args.output_root.resolve() / "manifest.json", pilot_manifest)
    summary = {
        "kind": "qwen_image21_official_control_partial_adaptive_summary",
        "protocol": (
            "official Qwen default Control; exact captured latent entering step 12; "
            "per-role tolerant v7 injection; 0.40 identity threshold selecting 1 or 6 steps"
        ),
        "results": all_results,
    }
    _write(args.output_root.resolve() / "summary.json", summary)
    print(json.dumps(summary, ensure_ascii=False, indent=2))


if __name__ == "__main__":
    main()
